# model url
websocket.modelServer.url=ws://localhost:8765
# web_url
web.url=*
websocket.webUser.url=/topic/face_fatigue/
face.camera.sample-interval-ms=1000
app.go2rtc.config-file=go2rtc/go2rtc.yaml
app.go2rtc.api-base=http://127.0.0.1:1984
spring.application.name=faceservice
server.port=8081
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
server.ssl.enabled=false
#server.ssl.certificate=face-service/src/main/resources/cert/server-cert.pem
#server.ssl.certificate-private-key=face-service/src/main/resources/cert/server-key.pem
